services:
  wikiless:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wikiless
    hostname: wikiless
    restart: always
    networks:
      - wikiless_net
    environment:
      REDIS_HOST: redis://wikiless_redis:6379
    ports:
      - "127.0.0.1:8180:8080" # change port if needed
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
        - wikiless_redis

  wikiless_redis:
    container_name: wikiless_redis
    hostname: wikiless_redis
    image: redis:latest
    restart: always
    networks:
      - wikiless_net
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
